name: Test Magento 2

on:
  push:
    branches: [ "dev-task" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up PHP 8.3
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: xdebug, pdo_mysql
        coverage: xdebug
        ini-values: memory_limit=2G, post_max_size=256M

    - name: Install Composer Dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Enable the module
      run: php bin/magento module:enable Custom_Purchased
      
    - name: Running DI Compilations
      run: php bin/magento setup:di:compile

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, xdebug
          coverage: xdebug

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader
        
      - name: Enable the module
        run: php bin/magento module:enable Custom_Purchased
      
      - name: Run PHPUnit on Custom Code
        run: php -d xdebug.mode=coverage vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist --coverage-html reports app/code/Custom

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: reports
